# Generated by Django 5.2.5 on 2025-08-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('text', 'source')},
        ),
    ]
