# Generated by Django 5.2.5 on 2025-08-29 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_quote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Вес (от 0 до 1)'),
        ),
    ]
