"""Константы бэкенда."""

SOURCE_NAME_MAX_LENGTH: int = 255
SOURCE_TYPE_MAX_LENGTH: int = 20
SOURCE_AUTHOR_MAX_LENGTH: int = 255
MAX_SOURCE_YEAR: int = 2100
NORMALIZED_TEXT_MAX_LENGTH: int = 2_000
SHOW_TEXT_LENGTH: int = 50
NUM_QUOTES_PER_PAGE: int = 10
NUM_SOURCES_PER_PAGE: int = 10
